### ISSUE TITLE
11_voronoi_otsu_labeling, text suggestion

### ISSUE THREAD

**Issue by fbnrst** [BiAPoL/Bio-image_Analysis_with_Python#17]
Concerning https://github.com/BiAPoL/Bio-image_Analysis_with_Python/blob/main/04_image_segmentation/11_voronoi_otsu_labeling.ipynb

look at this in this part of the notebook:

```markdown
## Applying the algorithm
Voronoi-Otsu-labeling is a **command in clesperanto**, which asks for two sigma parameters. The first sigma controls how close detected cells can be (`spot_sigma`) and second controls how precise segmented objects are outlined (`outline_sigma`). This is the algorithm implemented in the [napari-segment-blobs-and-things-with-membranes](https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes):
```

First you state it is a command in clesperanto, then you use napari-segment-blobs-and-things-with-membranes instead. This is a bit confusing. Probably you could just change the **command in clesperanto** to command in **napari-segment-blobs-and-things-with-membranes**

**Comment by haesleinhuepf** [comment]
Awesome, thanks for reporting @fbnrst !
