### ISSUE TITLE
napari OpenGL Mac (Big Sur)

### ISSUE THREAD

**Issue by filipponisini** [BiAPoL/Bio-image_Analysis_with_Python#3]
Did anyone found a solution to our problem using Napari on Mac?
After installing Napari and using this code:

import napari

# start napari
viewer = napari.Viewer()

# add image
viewer.add_image(image)

# add binary image as labels
labels = viewer.add_labels(binary_image)

...the Error-Message was:
"RuntimeError: Could not load OpenGL library, gl cannot be used"

**Comment by haesleinhuepf** [comment]
Hi @filipponisini ,

can you please try the solutions posted here:
https://forum.image.sc/t/napari-issues-on-bigsur/52630/13

Let us know if this helps!

Best,
Robert

**Comment by filipponisini** [comment]
hey @haesleinhuepf,

thank you! It worked.
